### ISSUE TITLE
v1.2 Roadmap

### ISSUE THREAD

**Issue by MMK21Hub** [MMK21Hub/Capitalisation-Fixes#1]
**Update: 1.2 is out!**

1.2 is coming soon! It will include bugfixes for the following:

- [x] https://bugs.mojang.com/browse/MC-187380
- [x] https://bugs.mojang.com/browse/MC-187379
- [x] https://bugs.mojang.com/browse/MC-187344
- [x] https://bugs.mojang.com/browse/MC-187544
- [x] https://bugs.mojang.com/browse/MC-187676
- [x] https://bugs.mojang.com/browse/MC-187677
- [x] https://bugs.mojang.com/browse/MC-188393

What's left to do?
 - [x] Test in-game
 - [x] Upload to GitHub
 - [x] Update README.md
 - [x] Create a new release

Note: [MC-188390](https://bugs.mojang.com/browse/MC-188390) has not been fixed, as it is up to Mojang to decide how to fix it. However, it may be included in a future release. [MC-188389](https://bugs.mojang.com/browse/MC-188389) is another one to watch.

[**Changelog**](https://github.com/MMK21Hub/Capitalisation-Fixes/blob/master/Changelog.md#v12)
