### ISSUE TITLE
v1.3 Roadmap

### ISSUE THREAD

**Issue by MMK21Hub** [MMK21Hub/Capitalisation-Fixes#2]
Yes, already! Work on this update won't start immediately, though.

Note: The bug tracker team [have decided](https://bugs.mojang.com/browse/MC-190108?focusedCommentId=732716&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-732716) to track all new capitalisation issues in [MC-190102](https://bugs.mojang.com/browse/MC-190102).

 - [x] Remove the fix for [MC-186264](https://bugs.mojang.com/browse/MC-186264)
 - [ ] https://bugs.mojang.com/browse/MC-188390
 - [ ] https://bugs.mojang.com/browse/MC-187546
 - [x] https://bugs.mojang.com/browse/MC-116857
 - [x] https://bugs.mojang.com/browse/MC-188389
 - [x] https://bugs.mojang.com/browse/MC-188392
 - [ ] https://bugs.mojang.com/browse/MC-190146
 - [ ] Add a pack.png (It's been a long time coming)

Boring tasks:
 - [ ] Test in-game
 - [ ] Upload to GitHub
 - [ ] Update README.md
 - [ ] Create a new release

**Comment by MMK21Hub** [comment]
Well, this isn't going to happen :p
