### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by MMK21Hub** [MMK21Hub/Capitalisation-Fixes#3]
### New string fixes
- [x] [Several 1.17 advancement strings](https://bugs.mojang.com/browse/MC-226430)
- [x] [Hide Lightning Flashes option description](https://bugs.mojang.com/browse/MC-236606)
- [x] ["Horse armor equips" subtitle](https://bugs.mojang.com/browse/MC-219541)
- [x] ["Include entities" button in the structure block interface](https://bugs.mojang.com/browse/MC-195781)
- [x] ["Data mode" and "Load mode" buttons in the structure block interface](https://bugs.mojang.com/browse/MC-195780)
- [x] ["Feels like home" advancement](https://bugs.mojang.com/browse/MC-237920)

### Other tasks
- [x] Bring the README up-to-date (again)
- [x] Finally create a pack.png
- [x] **Publish version**

**Comment by MMK21Hub** [comment]
Done! https://github.com/MMK21Hub/Capitalisation-Fixes/releases/tag/v2.0
